FROM python:3.12-slim

# Establece el directorio de trabajo
WORKDIR /app

# Copia requirements.txt y lo instala
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# Copia todo el contenido de la carpeta model al contenedor
COPY . ./model

# Establece el directorio de trabajo correcto
WORKDIR /app/model

# Crea la carpeta results si no existe
RUN mkdir -p results

# Define el volumen para persistir archivos .joblib de results
VOLUME ["/app/model/results"]

# Comando por defecto: ejecuta main.py usando Supabase (puedes pasarle argumentos al correr el contenedor)
CMD ["python", "-m", "eneagrama_predictor.main", "--mode", "train", "--questions", "80", "--model", "results/modelo_reducido.joblib"]