FROM python:3.12-slim

# Establece el directorio de trabajo
WORKDIR /app

# Copia requirements.txt de la raíz y lo instala
COPY ../requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# Copia todo el contenido de la carpeta model al contenedor
COPY . .

# Crea la carpeta results si no existe
RUN mkdir -p results

# Define el volumen para persistir archivos .joblib de results
VOLUME ["/app/results"]

# Comando por defecto: ejecuta main.py (puedes pasarle argumentos al correr el contenedor)
CMD ["python", "-m", "eneagrama_predictor.main", "--mode", "train", "--data", "eneagrama_predictor/data.csv", "--questions", "80", "--model", "modelo_reducido.joblib"]