FROM python:3.12-slim

WORKDIR /enneagram-web

# Copia requirements.txt e instala dependencias
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copia el resto de la app
COPY . .

# Expone el puerto (ajusta si usas otro)
EXPOSE 8080

# Comando para ejecutar la app (ajusta si usas otro framework o puerto)
CMD ["uvicorn", "api.app_new:app", "--host", "0.0.0.0", "--port", "8080"]